#!/bin/sh

file=$0
fileC=${file}.C
fileEXE=${file}.exe

ROOTLIBS="-L/usr/lib64 `$ROOTSYS/bin/root-config --glibs` -lMathCore -lMinuit"
ROOTINCDIR=`$ROOTSYS/bin/root-config --incdir`

BASETREEDIR="../src"

echo "[$0]: Compiling"
rootcling -f MuonPogTreeDict.C -c ${BASETREEDIR}/MuonPogTree.h ${BASETREEDIR}/MuonPogTreeLinkDef.h

g++ -g -std=gnu++11 -I${ROOTINCDIR} ${fileC} MuonPogTreeDict.C ${ROOTLIBS} -lX11 -lboost_system -lboost_filesystem -o ${fileEXE}

echo "[$0]: Running with parameters $@" 
${fileEXE} $@

rm MuonPogTreeDict* ${fileEXE}



