#!/bin/sh
SCRAM_ARCH=slc6_amd64_gcc530

file=$0
fileC=${file}.C
fileEXE=${file}.exe

ROOTLIBS="-L/usr/lib64 `$ROOTSYS/bin/root-config --glibs` -lMathCore -lMinuit"
ROOTINCDIR=`$ROOTSYS/bin/root-config --incdir`

BASETREEDIR="../src"

echo "[$0]: Compiling"
rootcling -f MuonPogTreeDict.C -c ${BASETREEDIR}/MuonPogTree.h ${BASETREEDIR}/MuonPogTreeLinkDef.h

g++ -std=gnu++1y -I${ROOTINCDIR} ${fileC} MuonPogTreeDict.C ${ROOTLIBS} -lX11 -o ${fileEXE}

echo "[$0]: Running with parameters $@" 
${fileEXE} $@

rm -f MuonPogTreeDict.C MuonPogTreeDict.h MuonPogTreeDict_rdict.pcm
rm -f ${fileEXE}
